name: Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'

    - name: 🌐 Build Web
      run: flutter build web --release

    - name: 🔑 Setup SSH (for cleanup & reload)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          # Очистить СОДЕРЖИМОЕ папки, но не саму папку
          rm -rf /var/www/lixemgang/*
          # Или, если есть скрытые файлы (редко для Flutter):
          # rm -rf /var/www/lixemgang/{*,.*}
          # Но осторожно с .* — можно удалить .well-known!

    - name: 🚀 Deploy with rsync
      uses: burnett01/rsync-deployments@v2.2
      with:
            switches: -av --delete
            path: build/web/
            remote_path: /var/www/lixemgang/
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_password: ${{ secrets.DEPLOY_PASSWORD }}

    - name: ✅ Reload nginx
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: sudo systemctl reload nginx